name: scolengo_api_dart
description: Unofficial API wrapper for the Skolengo education management system
version: 0.0.1
repository: https://github.com/lolocomotive/skolengo-api-dart

environment:
    sdk: '>=2.19.6 <3.0.0'

dev_dependencies:
    lints: ^2.0.0
    test: ^1.21.0
dependencies:
    http: ^0.13.5
    japx: ^2.1.0
    openid_client: ^0.4.7
